repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--quiet']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: double-quote-string-fixer
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear',  # Looks for likely bugs and design problems
          'flake8-comprehensions',  # Looks for unnecessary generator functions that can be converted to list comprehensions
          'flake8-deprecated',  # Looks for method deprecations
          'flake8-use-fstring',  # Enforces use of f-strings over .format and %s
          'flake8-print',  # Checks for print statements
          'flake8-docstrings',  # Verifies that all functions/methods have docstrings
          'flake8-type-checking',  # Looks for misconfigured type annotations
          'flake8-annotations',  # Enforces type annotation
        ]
        args: ['--enable-extensions=G']
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: 'django_guid/.*'
      - id: isort
        files: 'tests/.*'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
