name: Publish django-guid to PyPI and TestPyPI 📦

on: push

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-publish-pypi.txt
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish distribution of django-guid to Test PyPI 📦
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && contains(github.event.ref, '.rc')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution of django-guid to PyPI 📦
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && !contains(github.event.ref, '.rc')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
