name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - run: pip install pre-commit
      - uses: actions/cache@v3
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: key-1
      - run: pre-commit run --all-files
        env:
          SKIP: rst

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9.18", "3.10.13", "3.11.7", "3.12.1" ]
        django-version: [ "4.2", "5.0", "5.1" ]
        exclude:
          # Django v5 drops Python <3.10 support
          - django-version: 5.0
            python-version: 3.9.18
          - django-version: 5.1
            python-version: 3.9.18
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/cache@v3
        id: poetry-cache
        with:
          path: ~/.local
          key: key-5
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          version: 1.2.2
      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: ${{ hashFiles('**/poetry.lock') }}-6
      - run: |
          pip install virtualenv
          virtualenv .venv
          source .venv/bin/activate
          pip install pip setuptools wheel -U
          poetry install --no-interaction --no-root
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: |
          source .venv/bin/activate
          pip install "Django==${{ matrix.django-version }}"
      - name: Run tests
        run: |
          source .venv/bin/activate
          coverage run -m pytest tests
          coverage xml
          coverage report
      - uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
        if: matrix.python-version == '3.11'
